## Scrape configuration for OpenTelemetry Collector
## See https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config
scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 10s
    static_configs:
      - targets: ["otel-collector:8889"]